## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [5]:
import numpy as np
arr1=np.arange(start=50,stop=100)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [24]:
import numpy as np
arr1=np.ones((3,3))
arr2=np.pad(arr1,(1,1),'constant',constant_values=0)
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Convert a list and tuple into arrays

In [27]:
import numpy as np
mylist=[1,2,3,4,5]
outarr=np.asarray(mylist)
print(outarr)
mytuple=(6,7,8,9)
outarr1=np.asarray(mytuple)
print(outarr1)

[1 2 3 4 5]
[6 7 8 9]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [34]:
import numpy as np
arr1=np.array([ 0,12,45.21,34,99.91])
arr2=np.array([1.8])
arr3=arr1*arr2
arr4=np.array([32])
finalarray=arr3+arr4
print(finalarray)


[ 32.     53.6   113.378  93.2   211.838]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [39]:
import numpy as np
arry=np.array([[1,2,3,4],[5,6,7,8]])
# Size of the array  
print(arry.size) 
  
# Length of one array element in bytes, 
print( arry.itemsize) 
  
# Total bytes consumed by the elements  
# of the array 
print(arry.nbytes)

8
4
32


## Exercise 6: Get the unique elements of an array

In [41]:
import numpy as np
arry=np.array([10,10,20,20,30,30])
print("Original array:")
print(arry)
print("Unique elements of the above array:")
print(np.unique(arry))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]


## Exercise 7: Change the dimension of an array


In [45]:
import numpy as np
arry=np.array([1,2,3,4,5,6,7,8,9])
print('Original array:',arry)
print('Change array shape to (3, 3) -> 3 rows and 3 columns ',arry.reshape(3,3))

Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns  [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [46]:
import numpy as np
np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [55]:
import numpy as np
Array1=np.array([10,20,30])
Array2=np.array([40,50,60])
print(np.stack((Array1,Array2),axis=1))

[[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [67]:
import numpy as np
Array1=np.zeros((5,5))
print('Original Array',Array1)
Array2=np.arange(0,5)
Array3=Array1+Array2
print('Row values ranging from 0 to 4.',Array3)

Original Array [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4. [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [72]:
lst=[]
count=0
import numpy as np
for i in range (1,100):
    if i%3==0 or i%5==0:
        lst.append(i)
        count=count+i
Array1=np.array((lst))
print(Array1)
print(count)

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [73]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


In [78]:
import numpy as np
x = np.array([0,1,2,3])
y = np.array([[0,1,2,3],[4,5,6,7]])
for a, b in np.nditer([x,y]):
    print(a,':',b)
    

0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [82]:
import numpy as np
array1=np.array([[0.42436315, 0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581,  0.34528799, 0.1563123 ]])
print('Original array:',array1)
print('Replace all elements of the said array with .5 which are greater than .5',np.where(array1>0.5, 0.5, array1))

Original array: [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

In [84]:
import numpy as np
array1=np.empty((0,3),int)
print("The Empty Array")
print(array1)
array1=np.append(array1,np.array([[10,20,30]]),axis=0)
array1=np.append(array1,np.array([[40,50,60]]),axis=0)
print("After adding two new arrays:")
print(array1)

The Empty Array
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [85]:
arrs=np.array([1,2,3])
ars=np.array([2,3,4])
print(arrs,'\n',ars)
d=np.stack((arrs,ars))
print(d)

ap=arrs.reshape((3,1))
dp=ars.reshape((3,1))


print("Sequence of arrays along a new axis:\n",np.stack((ap,dp)).reshape(6,1))

[1 2 3] 
 [2 3 4]
[[1 2 3]
 [2 3 4]]
Sequence of arrays along a new axis:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
